global  ORIGEM DESTINO COMODITE DCARGA CARREGAMENTO CALADO PRAZO
global  NODE DIST
global  NOMEMB ARMADOR ENDERECO CEP ESTALEIRO NCASCO LOCONSTRUCAO ANOCON MATCASCO TIPOEMB PORTO CLASSIFICACAO TBL ANAV NINSCRICAO INCHAMADA AB AL
global  LBMAX BBMAX EXPESSURA
global  ENGE NCREA TEL
global  LB BB HB

clc

ORIGEM = 0;
DESTINO = 0;
COMODITE = 0;
DCARGA = 0;
CARREGAMENTO = 0;
CALADO = 0;
PRAZO = 0;

NODE = 0;
DIST = 0;

NOMEMB = 0;
ARMADOR = 0;
ENDERECO =0;
CEP = 0;
ESTALEIRO = 0;
NCASCO = 0;
LOCONSTRUCAO = 0;
ANOCON = 0;
MATCASCO = 0;
TIPOEMB = 0;
PORTO = 0;
CLASSIFICACAO = 0;
TBL = 0;
ANAV = 0;
NINSCRICAO = 0;
INCHAMADA = 0;
AB = 0;
AL = 0;

LBMAX = 0;
BBMAX = 0;
EXPESSURA = 0;

ENGE = 0;
NCREA = 0;
TEL = 0;

LB = 0;
BB = 0;
HB = 0;
